### ISSUE TITLE
blank response

### ISSUE THREAD

**Issue by szewang2805** [dangrossman/PHP-OpenCalais#2]
hi, i have already put the API key , but i get the error

( ! ) Fatal error: Uncaught exception 'OpenCalaisException' with message 'No response was received from the API.' in C:\wamp\www\test\opencalais.php on line 55

can you solve it?

Andy

**Comment by dangrossman** [comment]
Are you using an API key from the new OpenCalais site, and not the old API? Chances are it's a connection or authentication problem.

**Comment by szewang2805** [comment]
Yes. I m using the new api key from calais. It is from New.calais.com
May i send u my key to u for testing?
Thx
Andy
於 2015年6月29日 下午10:55，"Dan Grossman" notifications@github.com 寫道：
