### ISSUE TITLE
Importance attribute

### ISSUE THREAD

**Issue by buneme** [dangrossman/PHP-OpenCalais#4]
(For greater clarity view:http://stackoverflow.com/questions/31587050/opencalais-cant-view-importance-value)
OpenCalais sends an importance value for each socialTag, but I can't see it when I var_dump the socialTag.
![screen shot 2015-07-23 at 1 05 01 pm](https://cloud.githubusercontent.com/assets/3949246/8849923/84f15b94-313b-11e5-98c8-257728ef1a16.png)

**Comment by dangrossman** [comment]
This library does only one thing: returns an array of tag names. They are not objects, they have no properties. If you want to do something with the importance, you'll have to write new code.

**Comment by buneme** [comment]
okay, then what does this line of code do in the opencalis class:
                $this->entities[$item->_typeGroup][] = trim($item->name);

**Comment by dangrossman** [comment]
Adds the name of the tag to the array that's going to be returned.

**Comment by buneme** [comment]
okay, so to add the importance value would I do this:
$this->entities[$item->importance][] = trim($item->importance);
